Bugfix
NullPointerException bug occurred when the phone was being rotated
while initialising the Activity. The reason is that the Tread
responsible for downloading and showing the available weeks continued
to run and tried to show or hide the “Next week” buttons even though
they didn’t exist anymore (because of the Activity recreation caused by
the phone rotation). Simple null checking fixes this bug.

java.lang.NullPointerException: Attempt to invoke interface method
'android.view.MenuItem android.view.MenuItem.setEnabled(boolean)' on a
null object reference
	at
com.timodenk.gswnstupla.StuplaActivity.updateChangeWeekButtons(StuplaAct
ivity.java:172)